version: '3'

services:

  flyway:
    image: flyway/flyway
    #container_name: flyway
    volumes:
      - "./sql:/flyway/sql"
    environment:
      - FLYWAY_CONNECT_RETRIES=60
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
      - FLYWAY_SCHEMAS=${FLYWAY_SCHEMAS}
    command: -url=jdbc:postgresql://pgdb/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
    depends_on:
      - pgdb
    networks:
      - flynet

  pgdb:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    user: root
    ports:
      - "5432:5432"
    networks:
      - flynet

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "8080:80"
    networks:
      - flynet
    depends_on:
      - pgdb

networks:
  flynet:
